/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package digitalexamsystem;

import Project.Projectconnectionprovider;
import java.lang.System.Logger;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
public class addnewquestions extends javax.swing.JFrame {

    /**
     * Creates new form addnewquestions
     */
    public addnewquestions() {
        initComponents();
        try{
         Connection con=Projectconnectionprovider. getConnection(); 
         Statement st=con.createStatement();
         ResultSet rs=st.executeQuery("select count(ID) from questions");
           if(rs.next()){
               int id=rs.getInt(1);
               id=id+1;
               String str=String.valueOf(id);
               lblquestionid.setText(str);
           }
           else{
               lblquestionid.setText("1");
           }
        }
        catch(Exception e){
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtquestion = new javax.swing.JTextField();
        txtchoice1 = new javax.swing.JTextField();
        txtchoice2 = new javax.swing.JTextField();
        txtchoice3 = new javax.swing.JTextField();
        txtchoice4 = new javax.swing.JTextField();
        txtanswer = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        lblquestionid = new javax.swing.JLabel();
        btnclear = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(150, 183));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/digitalexamsystem/addnewquestion.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 6, 41, 60));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 40)); // NOI18N
        jLabel2.setText("Add New Question");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 401, 42));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 81, 1066, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/digitalexamsystem/Close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, 79, 69));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setText("Question ID:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setText("Question:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setText("Choice 1:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setText("Choice 2:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel7.setText("Choice 3:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel8.setText("Choice 4:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel9.setText("Answer:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 86, -1));

        txtquestion.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(txtquestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 147, 830, -1));

        txtchoice1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        txtchoice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtchoice1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtchoice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 197, 830, -1));

        txtchoice2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(txtchoice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 830, -1));

        txtchoice3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(txtchoice3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 830, -1));

        txtchoice4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(txtchoice4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 830, -1));

        txtanswer.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        txtanswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtanswerActionPerformed(evt);
            }
        });
        getContentPane().add(txtanswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 830, -1));

        btnsave.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/digitalexamsystem/save.png"))); // NOI18N
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, -1, 40));

        lblquestionid.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblquestionid.setForeground(new java.awt.Color(255, 0, 0));
        lblquestionid.setText("00");
        getContentPane().add(lblquestionid, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 41, -1));

        btnclear.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/digitalexamsystem/clear2.png"))); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, -1, -1));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(845, 458, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/digitalexamsystem/pages background admin.jpg"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtchoice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtchoice1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtchoice1ActionPerformed

    private void txtanswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtanswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtanswerActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        try{
        String id=lblquestionid.getText();
        String question=txtquestion.getText();
        String opt1=txtchoice1.getText();
        String opt2=txtchoice2.getText();
        String opt3=txtchoice3.getText();
        String opt4=txtchoice4.getText();
        String ans=txtanswer.getText();
        if(question.equals("")||opt1.equals("")||opt2.equals("")||opt3.equals("")||opt4.equals("")||ans.equals("")){
            JOptionPane.showMessageDialog(null,"Some Fields Are Empty");
        }
        else{
      Connection con=Projectconnectionprovider. getConnection(); 
      PreparedStatement ps=con.prepareStatement("insert into questions(ID,questions,Option1,Option2,Option3,Option4,answer) values(?,?,?,?,?,?,?)");
      ps.setString(1,id);
      ps.setString(2,question);
      ps.setString(3,opt1);
      ps.setString(4,opt2);
      ps.setString(5,opt3);
      ps.setString(6,opt4);
      ps.setString(7,ans);
     ps.executeUpdate();
           JFrame jf=new JFrame();
           jf.setAlwaysOnTop(true);
           JOptionPane.showMessageDialog(jf,"Question inserted succsessfully");
           setVisible(false);
           new addnewquestions().setVisible(true);
    }//GEN-LAST:event_btnsaveActionPerformed

        }catch (Exception ex) {
         JFrame jf=new JFrame();
           jf.setAlwaysOnTop(true);
           JOptionPane.showMessageDialog(jf,ex);
    
    }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       AdminHome.opan=0;
       setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
      
        txtquestion.setText("");
        txtchoice1.setText("");
        txtchoice2.setText(" ");
        txtchoice3.setText("");
        txtchoice4.setText("");
        txtanswer.setText("");
    }//GEN-LAST:event_btnclearActionPerformed
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addnewquestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addnewquestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addnewquestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addnewquestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addnewquestions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblquestionid;
    private javax.swing.JTextField txtanswer;
    private javax.swing.JTextField txtchoice1;
    private javax.swing.JTextField txtchoice2;
    private javax.swing.JTextField txtchoice3;
    private javax.swing.JTextField txtchoice4;
    private javax.swing.JTextField txtquestion;
    // End of variables declaration//GEN-END:variables
}
