/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package digitalexamsystem;

import java.sql.*;
import Project.Projectconnectionprovider;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
public class Deletequestion extends javax.swing.JFrame {

    /**
     * Creates new form Deletequestion
     */
    public Deletequestion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btndeleteclose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtiddelete = new javax.swing.JTextField();
        txtquestiondelete = new javax.swing.JTextField();
        txtchoice1delete = new javax.swing.JTextField();
        txtchoice2delete = new javax.swing.JTextField();
        txtchoice3delete = new javax.swing.JTextField();
        txtchoice4delete = new javax.swing.JTextField();
        txtanswerdelete = new javax.swing.JTextField();
        btnsearchdelete = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(150, 183));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btndeleteclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/digitalexamsystem/Close.png"))); // NOI18N
        btndeleteclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletecloseActionPerformed(evt);
            }
        });
        getContentPane().add(btndeleteclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(972, 15, 79, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/digitalexamsystem/delete Question.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 15, -1, 69));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 40)); // NOI18N
        jLabel2.setText("Delete Question");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 15, 362, 60));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 93, 1066, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setText("Question ID:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setText("Question:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 158, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setText("Choice 1:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 203, -1, 33));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setText("Choice 2:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 254, -1, 33));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel7.setText("Choice 3:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 305, -1, 33));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel8.setText("Choice 4:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 362, -1, 33));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel9.setText("Answer:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 413, -1, -1));

        txtiddelete.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(txtiddelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 220, 30));

        txtquestiondelete.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(txtquestiondelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 701, 33));

        txtchoice1delete.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(txtchoice1delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 701, 33));

        txtchoice2delete.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(txtchoice2delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 701, 33));

        txtchoice3delete.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(txtchoice3delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 701, 33));

        txtchoice4delete.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(txtchoice4delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 701, 33));

        txtanswerdelete.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(txtanswerdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 701, 33));

        btnsearchdelete.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnsearchdelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/digitalexamsystem/search.png"))); // NOI18N
        btnsearchdelete.setText("search");
        btnsearchdelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsearchdeleteMouseClicked(evt);
            }
        });
        btnsearchdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchdeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnsearchdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, 30));

        btndelete.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/digitalexamsystem/delete2.png"))); // NOI18N
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, -1, -1));

        btnclear.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/digitalexamsystem/clear2.png"))); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 125, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/digitalexamsystem/pages background admin.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndeletecloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletecloseActionPerformed
        AdminHome.opan=0;
        setVisible(false);
    }//GEN-LAST:event_btndeletecloseActionPerformed

    private void btnsearchdeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsearchdeleteMouseClicked
       String id=txtiddelete.getText();
       try{
          Connection con= Projectconnectionprovider.getConnection();
          Statement st=con.createStatement();
          String query=("select * from questions where ID='"+id+"'");
          ResultSet rs=st.executeQuery(query);
             if(rs.next()){
                 txtquestiondelete.setText(rs.getString(3));
                 txtchoice1delete.setText(rs.getString(4));
                 txtchoice2delete.setText(rs.getString(5));
                 txtchoice3delete.setText(rs.getString(6));
                 txtchoice4delete.setText(rs.getString(7));
                 txtanswerdelete.setText(rs.getString(8));
                txtiddelete.setEditable(false);
             }
             else{
                 JFrame jf=new JFrame();
                 jf.setAlwaysOnTop(true);
                 JOptionPane.showMessageDialog(jf,"Question ID dosen't Exist");
             }
       }
       catch(Exception e){
                 JFrame jf=new JFrame();
                 jf.setAlwaysOnTop(true);
                 JOptionPane.showMessageDialog(jf,e);
       }
    }//GEN-LAST:event_btnsearchdeleteMouseClicked

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
       String id=txtiddelete.getText();
       try{
           Connection cn=Projectconnectionprovider.getConnection();
           PreparedStatement ps=cn.prepareStatement("delete from questions where id=?");
           ps.setString(1, id);
           ps.executeUpdate();
           JFrame jf=new JFrame();
           jf.setAlwaysOnTop(true);
           JOptionPane.showMessageDialog(jf,"Successufully Deleted");
           setVisible(false);
           new Deletequestion().setVisible(true);
       }
       catch(Exception e){
           JFrame jf=new JFrame();
                 jf.setAlwaysOnTop(true);
                 JOptionPane.showMessageDialog(jf,e);
       }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
           txtiddelete.setText("");
           txtquestiondelete.setText("");
           txtchoice1delete.setText("");
           txtchoice2delete.setText("");
           txtchoice3delete.setText("");
           txtchoice4delete.setText("");
           txtanswerdelete.setText("");
           txtiddelete.setEditable(true);
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnsearchdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchdeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsearchdeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Deletequestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Deletequestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Deletequestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Deletequestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Deletequestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btndeleteclose;
    private javax.swing.JButton btnsearchdelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtanswerdelete;
    private javax.swing.JTextField txtchoice1delete;
    private javax.swing.JTextField txtchoice2delete;
    private javax.swing.JTextField txtchoice3delete;
    private javax.swing.JTextField txtchoice4delete;
    private javax.swing.JTextField txtiddelete;
    private javax.swing.JTextField txtquestiondelete;
    // End of variables declaration//GEN-END:variables
}
